### ISSUE TITLE
SublimeLinter 4 will stop supporting inline settings

### ISSUE THREAD

**Issue by braver** [jasjuang/SublimeLinter-contrib-cmakelint#1]
We're making big changes to SublimeLinter and version 4 will no longer support inline settings. Users should migrate to configuration features of their particular linter. Please consider updating this plugin to reflect this deprecation. If you have any questions, let me know!

**Comment by jasjuang** [comment]
@braver Thanks for the heads up. Is there a guide anywhere (or a sample repo) that I can follow to migrate from inline settings to configuration features?

**Comment by braver** [comment]
I see that cmakelint accepts a cmakelintrc configuration file, users should be encouraged to configure cmakelint that way instead of via SublimeLinter settings.

**Comment by jasjuang** [comment]
@braver I pushed a commit similar to yours at https://github.com/SublimeLinter/SublimeLinter-cpplint/commit/8f5dd87246301060511456c7b8c7ffa001b35d72 

Can you take a look and see whether anymore has to be changed?

**Comment by braver** [comment]
Yeah, that looks good to me. Eventually some stuff can be cleaned up in linter.py, `comment_re`, `inline_settings` and `inline_overrides` will stop doing anything in SL4. However, I generally opt to give everyone a grace period to prepare the move to SL4.

**Comment by jasjuang** [comment]
@braver Thanks for the review! Once you make the clean up for SublimeLinter-cpplint, I will follow as well.
