### ISSUE TITLE
"cmd" executable name wrong

### ISSUE THREAD

**Issue by MarioHenze** [jasjuang/SublimeLinter-contrib-cmakelint#5]
I suspect the executable name in the "cmd" property in linter.py is wrong. Trying to use the cmake linter results in the following error message in Sublimes Console: "SublimeLinter: WARNING: cmakelint cannot locate 'cmakelint'". I have properly installed cmake lint trough pip and can call cmake-lint.exe (notice the dash) in powershell. I am on Windows 10 x64, if it matters.

Therefore I would propose to change the following line in linter.py:
`cmd = ('cmakelint', '${args}', '${file}')`
into
`cmd = ('cmake-lint', '${args}', '${file}')`

**Comment by jasjuang** [comment]
I just checked mine, and it's still cmakelint.exe after I uninstall and install it again. In the python pip site https://pypi.org/project/cmakelint/, it also still shows it's cmakelint instead of cmake-lint. I am on Windows 10 x64 too. 

What exact command did you use to install cmakelint?

**Comment by MarioHenze** [comment]
Oh, I have realized the problem: I got tripped up somehow while installing `cmakelang` and `cmakelint` packages in pip. On my system only the `cmakelang` package was installed. This package also provides a cmake-lint executable. Additionally installing the `cmakelint` package fixed my problem.
